# Generated by Django 3.1.7 on 2021-03-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210318_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savemodel',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
